### PR TITLE
Fresh eyes see lurking typos :P

### PR DESCRIPTION
**Pull request by gogamoga**

### CODE REVIEW

**Comment by unscriptable** [comment]
lol. I'm not sure this was a typo! I think the intent was to combine the words "automatic" and "magic".  :)  

Do you think the "automagic" spelling is confusing?

**Comment by gogamoga** [comment]
automagic is fine
but then, it would be automagically and not automatigally

2014-02-20 15:35 GMT+02:00 John Hann notifications@github.com:

**Comment by gogamoga** [comment]
p.s. submiting new issue

2014-02-20 15:36 GMT+02:00 Goga Moga gogamoga@gmail.com:

**Comment by unscriptable** [comment]
Oh ha! I didn't notice!

**Comment by gogamoga** [comment]
fresh eyes :P!

2014-02-20 15:37 GMT+02:00 John Hann notifications@github.com:

**Comment by gogamoga** [comment]
issue is here: https://github.com/know-cujojs/hello/issues/2
related to main site (cujojs.com)

2014-02-20 15:39 GMT+02:00 Goga Moga gogamoga@gmail.com:

**Pull request merged**
