### PR TITLE
Update to when 3 !

### PR DESCRIPTION
**Pull request by fabricematrat**
Tested with when 3 to avoid the bower question as rest 1.1 is using when 3

### CODE REVIEW

**Comment by briancavalier** [comment]
This looks good.  I have no idea why, but when I pull it and run a clean bower install (ie I remove bower_components), it installs when 3.0.0, rather than the latest 3.x.x (3.4.2 as of right now).  I don't understand why that would happen.  Any ideas?  Maybe I'm doing something wrong ...

**Comment by fabricematrat** [comment]
I think it comes from msgs
msgs#0.3.3 has a dependency :
when#>1.0.0 <=3.0.0 which resolved to 3.0.0

https://github.com/cujojs/msgs/blob/v0.3.3/bower.json#L6

Shall we upgrade to 0.4 ?

On Sun, Jul 27, 2014 at 3:32 AM, Brian Cavalier notifications@github.com
wrote:

> This looks good. I have no idea why, but when I pull it and run a clean
> bower install (ie I remove bower_components), it installs when 3.0.0,
> rather than the latest 3.x.x (3.4.2 as of right now). I don't understand
> why that would happen. Any ideas? Maybe I'm doing something wrong ...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cujojs/seed/pull/13#issuecomment-50253121.

## 

Best regards,

┏( ＾◡＾)┛ ┗(＾◡＾ )┓ I rock RaveJS! ┏( ＾◡＾)┛ ┗(＾◡＾ )┓

http://rivieragug.org/
http://3musket33rs.github.com/
http://fabricematrat.github.io/

**Comment by briancavalier** [comment]
Ah, good catch.  Yeah, go ahead and update to msgs 0.4.  Thanks!

**Comment by fabricematrat** [comment]
Done !

On Sun, Jul 27, 2014 at 8:01 PM, Brian Cavalier notifications@github.com
wrote:

> Ah, good catch. Yeah, go ahead and update to msgs 0.4. Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cujojs/seed/pull/13#issuecomment-50280720.

## 

Best regards,

┏( ＾◡＾)┛ ┗(＾◡＾ )┓ I rock RaveJS! ┏( ＾◡＾)┛ ┗(＾◡＾ )┓

http://rivieragug.org/
http://3musket33rs.github.com/
http://fabricematrat.github.io/

**Comment by briancavalier** [comment]
Nice, thanks!

**Comment by unscriptable** [comment]
Thanks @fabricematrat!

**Pull request merged**
